### ISSUE TITLE
"String\UI". File not found

### ISSUE THREAD

**Issue by L30Bola** [FayneAldan/SVRichPresence#2] opened 2018-07-16 23:38 UTC
I reported the bug on [Nexus](https://www.nexusmods.com/stardewvalley/mods/2156?tab=bugs), so I'm reporting it here too, just to make thing easier. I've searched and found (what appears to be) the typo. I'm not acquainted with C#, so I can be wrong. I'll try to follow the [SMAPI Testing and Releasing Guide](https://stardewvalleywiki.com/Modding:Modder_Guide/Testing_and_Releasing), to compile and test the mod, so I can verify if I'm correct.

Below is the (what appears to be) the typo:
https://github.com/FayneAldan/SVRichPresence/blob/4ed4a331cc847710f3ed403b1a96363ef98b31d2/SVRichPresence/RichPresenceMod.cs#L202

**Comment by FayneAldan** [comment] 2018-07-16 23:42
Duplicate of #1. I already have it fixed on my end. Tested it and works. Just need to push it out.

**Closed by FayneAldan** 2018-07-16 23:42 UTC

**Comment by L30Bola** [comment] 2018-07-16 23:57
Oh, sorry. Should've used the search D:
